project:
  type: website

website:
  title: "Nuclear Correlates Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sources.qmd
      - model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



